replit/kaboom

- site/api.js
Just noticed that `rgb` had the `a` argument in the docs.
> Removed extra argument for `rgb` in documentation

- site/pub/guide/10.js
- site/pub/guide/11.js
- site/pub/guide/12.js
- site/pub/guide/13.js
- site/pub/guide/14.js
- site/pub/guide/15.js
- site/pub/guide/16.js
- site/pub/guide/17.js
- site/pub/guide/18.js
- site/pub/guide/3.js
- site/pub/guide/4.js
- site/pub/guide/5.js
- site/pub/guide/6.js
- site/pub/guide/7.js
- site/pub/guide/8.js
- site/pub/guide/9.js
Due to `kaboom.global()` being removed from the `genGame.js` script in this commit:
https://github.com/replit/kaboom/commit/e480fb5bf5c252b36e7325e79f83dc9c2f8d8c38#diff-0ddd15db301bfe15cb6bda312966ae5695dae3bd45a7fdddef4d50246e230837L63
The site guide doesn't load the sprites etc.
I've replicated what you have done in another commit for the examples, but it needs to be done for the interactive guide too.
Let me know if you need any other changes.
Many thanks!
> Add kaboom global to site guide

- src/kaboom.js
Hi! Brilliant library, it's lots of fun to make stuff with!
I noticed if you add the pressed key as an argument to the callback functions it allows for some powerful functionality like the ability to make quick input/dialog prompts to the user such as "Enter your name...".
Example code:
```
keyPress([ASCII_CHARS], (key) => {
if (gameState.promptOpen) {
promptInput(key);
}
});
```
Perhaps there is already an easy way to do this though that I just missed!
Many Thanks!
> Include key when calling keypress callback functions.

- site/api.js
- site/pub/examples/drive.js
The car animation is broken on the example due Aseprite support being ported over to `loadAseprite()` in kaboom version `0.2.0` instead of using it inside of a parameter inside of `loadSprite()`.
Animation now runs succesfully.
Also updated the documentation for `loadAseprite()`as well.
> Fix drive example car animation reference

- examples/button.js
There was an error in the Button example:
So I fixed it, and it now works as intended:
> FIX typeError cannot redefine property width

- site/api.js
As stated in this comment https://github.com/replit/kaboom/pull/91#issuecomment-874288963 the `resolve` method is now called `pushOutAll`.
I updated the API documentation to reflect this change.
> api.js: replace resolve with pushOutAll

- src/kaboom.ts
Creates a dynamic type based on what's passed into the kaboom.add method.
This will merge the type of each object in an array and return that combined object.
It's often difficult to prove TypeScript changes, but here's an example in screenshots:
Before:
Limited list of suggestions - Only GameObj properties are suggested.
No valid IntelliSense for functions on any of the Comp's passed into the add method.
After: 
Full list of IntelliSense suggestions
Correct IntelliSense for available methods.
This is my first time using kaboom, so bear with me. Open to feedback :)
> Add complex type for add method

- src/kaboom.ts
- src/types.ts
Objects on the same layer cann be ordered with `z(value: number)` comp.
Closes #167
> Add z index comp

- src/app.ts
Fixes #213
Added the cross browser calls in the fullscreen function defined in app.ts.
Caveats:
- It works on Google Chrome
- It works on Safari Experimental Build for OS X
- Does not work on current Safari stable version
- Does not work on last iOS Safari stable version
- For mobile version, I recommend using Capacitor or Cordova and packing a native app.
Needs help with:
- Testing in Mozilla Firefox
- Testing with MS Edge
> Added support to x-browser fullscreen

- CHANGELOG.md
- src/gfx.ts
- src/kaboom.ts
- src/types.ts
`clearColor` is more of word from webgl, not as intuitive as the word `background`, confused some users.
> rename clearColor to background

- package.json
- src/kaboom.ts
- fixed a typo that's causing objects to check collisions with themselves
- publishes the fix
> fix collides() checking for the same obj

- src/kaboom.ts
Some rearrangement to make stuff more clear. Also fixes a bug where `screenshot()` gives blank image because it's called after `gfx.frameStart()` which clears the canvas.
- broke `gameFrame()` into `updateFrame()` and `drawFrame()`
- moved the loading screen drawing code into `drawLoadScreen()`
- moved `drawInspect()` to a place near `app.run()` where it's called
> Clean game loop code

- src/kaboom.ts
#375 
On touch devices `mousePos` is updated on touch anyway, so `isMouseDown()` is kinda an no-op
> Don't special case for hover event on touch device

- src/kaboom.ts
- src/types.ts
#386
`GameObj#is()` always supported checking for multiple tags, it makes sense to support multiple tags for `get()` and `every()` too
> Support multiple tags on get() and every()

- demo/burp.js
- demo/eatbomb.js
- demo/flappy.js
- demo/out.js
- demo/pointclick.js
- demo/runner.js
- src/app.ts
- src/kaboom.ts
- src/types.ts
- Support adding the first argument to `onMouseXXX` to specify which button to listen to
```js
onMousePress("right", showMyMenu)
```
- Renamed `onMouseClick` to `onMousePress` to share a similar naming style like `onKeyPress`, support `onClick` without the first `tag` argument to catch all moue click events. Removed `onMouseClick` in favor of `onMousePress` or `onClick`
```js
// before
onMouseClick(dragPlayer);
// after
onClick(dragPlayer);
```
> Support all mouse buttons

- src/gfx.ts
- src/kaboom.ts
- src/types.ts
The main use case is to get the size of the text without rendering it. It's used internally in various places to draw text backgrounds, nice to expose.
And renamed from previously internal `fmtText()` to `formatText()`, `drawFmtText()` to `drawFormattedText()`
> Expose formatText() and drawFormattedText()

- src/types.ts
For some reason the sequence `@",` at that position breaks the markdown render
> Fix addLevel() doc markdown break

- src/kaboom.ts
The states are an array of strings, but the comparison is done as if it were a dictionary.
I believe the code should be: if (stateList && !stateList.includes(state))
which seems more sensible to me.
> enterState check fail fix

- src/kaboom.ts
Currently `state()` component will always report error if you don't bind an `onStateUpdate()` event (the `update()` hook will try to access the event handlers), due to the state events are not initialized unless you bind an event.
This PR wraps the event trigger and register in `on()` and `trigger()` helpers to make sure there's always initialization before usage.
> Fix missing state event not initilized in some cases

- CHANGELOG.md
- src/kaboom.ts
- src/types.ts
As proposed in [this comment](https://github.com/replit/kaboom/pull/346#pullrequestreview-789795171)
```js
const s = state("move", [ "idle", "attack", "move", ], {
"idle": [ "move", "attack" ],
"attack": "idle",
"move": "attack",
})
// define event for specific transitions
s.onStateTransition("move", "attack", throwFeces)
```
> Add transition guard to state()

- CHANGELOG.md
- demo/text.js
- src/gfx.ts
- src/kaboom.ts
- src/types.ts
Added a special syntax to enable style chunks of text
```js
drawText({
text: "(oh hi):green this is a (styled):wavy text",
styles: {
"green": (idx, ch) => ({
color: GREEN,
}),
"wavy": (idx, ch) => ({
color: BLUE,
pos: vec2(0, wave(-4, 4, time() * 4 + idx * 0.5)),
}),
},
})
```
Another idea is to use [BBCode](https://en.wikipedia.org/wiki/BBCode) syntax (implemented in #432)
```js
"[green]oh hi[/green] this is a [wavy]styled[/wavy] text"
```
> [RFC] Add syntax to style chunks of text

- CHANGELOG.md
- src/gfx.ts
- src/kaboom.ts
- src/math.ts
- src/types.ts
`dir()` is unintuitive and takes a very generic name spot
> Rename dir() to vec2FromAngle()

- src/gfx.ts
Character index tracking got out of sync due to
- the first index wrongfully starts with `1`
- styled chunk character local index is not taking consideration of index offset
- `\n` got omitted when forming formatted char list, however the style char index is recording the position with those `\n`s
> Fix text style parsing weirdness

- site/comps/Nav.tsx
The documentation navbar can be difficult to use on laptops or smaller
resolution devices due to needing to scroll down the list of section
names after a search query. Instead, filter the section names out of the
list if they don't have any matching entries.
> docs: Filter section names by search

- src/app.ts
Fixes [#450](https://github.com/replit/kaboom/issues/450). Adds a flag, `isKeyReleased`, which enables listening to an event when any key is released, rather than only specific keys specified in the event handler.
This PR matches the implementation of `isKeyDown`.
> fix: Allow onKeyReleased to check if any key is released

- package.json
Currently kaboom doesn't work with npm if you install with git repo `npm install replit/kaboom`
"prepare" runs before "prepack", which also runs when package is installed via github where `dist/` is `.gitignore`-ed
> Build on npm script "prepare" instead of "prepack"

- src/gfx.ts
Since #410 we're using shader uniform to apply camera instead of calculating the transformed vertices on CPU, the final vertices we calculate in `drawRaw` are world-space instead of screen-space due to this change, making the bound checking pointless if any camera transformation is involved. The direct effect is objects outside of [0, 0] - [width, height] were not rendered despite being in camera.
Should fix [this](https://github.com/replit/kaboom/pull/405#issuecomment-979701128)
> Disable automatic culling

- README.md
Use correct wording in the README documentation.
> docs: use proper naming convention

- site/comps/Nav.tsx
A tiny, yet subtle update to ensure we're using proper name convention.
> docs: use proper naming convention for GitHub

- demo/platformer.js
- src/kaboom.ts
- src/types.ts
`gravityScale` seems to be a better name, since the number is literally the scale to gravity.
`weight` might be used in the future to define how much an object can push another object
> [RFC] `weight` -> `gravityScale`

- src/gfx.ts
- src/types.ts
According to [this](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices#avoid_changing_vao_attachments_vertexattribpointer_disableenablevertexattribarray) it might help performance. We're only using one vertex layout now anyway.
> Only bind webgl vertex attribs once

- src/kaboom.ts
- src/types.ts
Currently doesn't support area for children game objects yet, turning it off until the next major release. 
Also as a result don't deprecate layers yet.
> Don't allow children game objects yet

- CHANGELOG.md
- src/kaboom.ts
- src/types.ts
- fix `toWorld()` to return the correct position transformed by camera
- deprecate `mouseWorldPos()` in favor of `toWorld(mousePos())`
> fix toWorld(), deprecate mouseWorldPos()

- CHANGELOG.md
- scripts/build.js
- scripts/dev.js
- site/comps/Doc.tsx
- src/kaboom.ts
- src/math.ts
- src/timer.ts
- src/types.ts
- src/utils.ts
For some structures like `Color`, `Vec2`, `Timer`, `Line` it makes more sense to be a `class` instead of factory + closed vars, so it can be `instanceof` and have `static`. 
`class` should also be faster than factory methods, however esbuild seems to add overhead to classes with the current setting, will investigate later.
> Make some structure classes

- scripts/build.js
The biggest source of kaboom slowness is esbuild generating polyfills for new js features like spread args, disabling it nearly doubles the performance. It's better to just don't use new features if there's breakage.
> Make esbuild not generate polyfills

- src/kaboom.ts
There's a logic error that makes the game not updating at all when `kaboom({ debug: false })`, and we actually don't have to check for `gopt.debug` here
> Fix not updating anything when debug is set to false

- src/types.ts
I noticed it for https://kaboomjs.com/#vec2 and felt it should be up to date.
> Replace deprecated dir() with Vec2.fromAngle()

- src/kaboom.ts
- src/types.ts
`focus()` just calls `canvas.focus()` which is trivial to write, however it conflicts with [`window.focus()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/focus) and messes up typescript
> Remove focus()

- CHANGELOG.md
- demo/layer.js
- src/kaboom.ts
- src/types.ts
The functionality of layers can be converged into parent game objects, making it an redundant system.
Old
```js
kaboom()
loadSprite("bean", "/sprites/bean.png")
// layer "ui" will be on top of layer "game", with "game" layer being the default
layers([
"game",
"ui",
], "game")
add([
sprite("bean"),
scale(5),
// specify layer with layer() component
layer("ui"),
color(0, 0, 255),
])
// this obj doesn't have a layer() component, fallback on default "game" layer
add([
sprite("bean"),
pos(100, 100),
scale(5),
])
```
New
```js
kaboom()
loadSprite("bean", "/sprites/bean.png")
// Create a parent node that won't be affected by camera (fixed) and will be drawn on top (z of 100)
const ui = add([
fixed(),
z(100),
])
// This will be on top, because the parent node has z(100)
ui.add([
sprite("bean"), …
```
> Remove layers in favor of parent game obj

- CHANGELOG.md
- src/kaboom.ts
- src/types.ts
Kaboom didn't properly handle device pixel density, leading to blurry rendering. This PR properly handle device pixel density, also exposes an option like
```js
kaboom({
pixelDensity: 4,
})
```
to further configure the pixel density (similar to p5's [`pixelDensity()`](https://p5js.org/reference/#/p5/pixelDensity))
Before:
After:
When `pixeldensity: 4`
> Support pixel density

- demo/loader.js
- demo/spriteatlas.js
- src/kaboom.ts
- src/types.ts
- src/utils.ts
Enables:
```js
const spr = loadSprite("me", "src/me.png")
// multiple onLoad / onError events
spr.onLoad(() => {
debug.log("hi")
})
spr.onLoad(() => {
debug.log("hi again!")
})
spr.onError((err) => {
debug.log("oh no!")
}).onError((err) => {
debug.log("oh no again!")
})
spr.done // Query the state
spr.error // or access the error if threw
spr.data // Get the asset data directly from the handle
// can use the handle directly 
add([ sprite(spr) ])
drawSprite(() => {
sprite: spr
})
```
> Add Asset wrapper type

- src/kaboom.ts
- src/types.ts
Caching every single new text can be very memory intensive especially if there's text animation, or it just changes a lot. Limit it the only caching 128 text textures for now.
> Limit text2d cache

- CHANGELOG.md
- demo/.eslintrc.json
- demo/draw.js
- demo/text.js
- src/kaboom.ts
- src/types.ts
Build a texture atlas on the go. When see uncached character, use canvas 2d to draw that character to offscreen canvas, `getImageData()` and upload image to a 1024x1024 texture atlas and store / cache the quad data to a map similar to bitmap font.
The result looks kinda decent (image below using built-in `"Sans-Serif"` font)
Also had to refactor the text formatting logic a bit to support variant width characters
> Convert non bitmap fonts to bitmap fonts on the fly

- CHANGELOG.md
- src/kaboom.ts
- src/types.ts
Added an error screen like this
also added 
```js
onError((err: Error) => {
// ...
})
```
error handling, or even custom error screen
> Improve error handling screen, allow register error event or customize error screen

- src/kaboom.ts
Before:
After:
Removes the hard coded padding for text, added generic padding to `drawUVQuad()` which applies to anything that uses texture like sprites. The padding is a workaround to floating point imprecision (the uv coordinates are all very small floating point values, which I guess is the problem)
> Add generic texture coordinate padding to remove rendering artifacts

- package.json
- scripts/build.js
https://github.com/replit/kaboom/pull/576#issuecomment-1110123131
Use
```ts
import "kaboom/global"
```
to import defs for the global functions, instead of a separate package
Using typescript's [`typeVersions`](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#version-selection-with-typesversions) field to export types on a certain subpath (helped by the example [here](https://github.com/teppeis/typescript-subpath-exports-workaround))
> Use subpath for global export

- demo/hover.js
- src/kaboom.ts
- src/types.ts
- Use closed variable in `Area#onHover()` and `Area#onHoverEnd()` instead of states
- Used another approach for global `onHover()` etc events to reduce all future custom logic for these global event handlers, see new helper `forAllCurrentAndFuture()`
> Fix hover events

- src/types.ts
The keys: 'shift', 'control', and 'alt' were missing from the Key type which was causing errors in typescript.
> adds shift, control, and alt to Key type

- src/gamepad.json
- src/types.ts
This PR adds support for using Nintendo's Joy-Con's individually (only the left one or only the right one) as well as for their Pro Controller. It also fixes the mapping for some buttons when using both L+R as a single controller.
I also added two new possible values for the `GamepadButton` type to allow users to use the `home` and `capture` buttons in their games. This is something that we might wanna rename to standardise across vendors (I know Sony also has a `home` button and they added one to `share` in their PS4 controller but this one would probably be mapped to `select`).
----
I would also like to allow users to pass on their custom gamepad definitions via `KaboomOpt`. This would allow them to extend `GAMEPAD_MAP` locally or even overwrite core mappings in case this is something …
> Improve gamepad support

- examples/multigamepad.js
- package-lock.json
- src/app.ts
- src/kaboom.ts
- src/types.ts
There's the update of the first gamepad pr.
Now Kaboom has a `mergedGamepadState`, where is combined all gamepads inputs, and a `gamepadsState`, where is each gamepad state. Now, `getGamepads()` works, and returns every gamepad registered by Kaboom.
```js
const gamepads = getGamepads();
gamepads[0].isPressed(); 
gamepads[1].isDown();
gamepads[2].isReleased();
gamepads[3].getStick();
gamepads[4].index // the index in the browser count of gamepads
```
> Kaboom gamepads

- src/types.ts
```ts
const plugin = (k: KaboomCtx) => {
return {
/** Returns the comp 1 */
myComp1() {},
};
};
const plugin2 = (k: KaboomCtx) => {
return {
/** Returns the comp 2 */
myComp2() {},
};
};
const k = kaboom({
plugins: [plugin, plugin2],
});
k.myComp1(); // OK
k.myComp2(); // OK
```
> add typing for plugins in `kaboom()` returns

- src/kaboom.ts
This e.g. happens with iframes.
Seems to fix #466
For ref see:
- https://sentry.io/answers/script-error/
- https://scoutapm.com/blog/script-errors
> fix: ignore errors from other sources

- src/kaboom.ts
- src/types.ts
If there is not a plugins property inside `KaboomOpt`, it only returns `KaboomCtx`
**Before**
**Now**
Now there's a support for options in plugins
**Normal plugins**
```ts
function logPlugin(k: KaboomCtx) {
return {
logWidth() {
return {
id: "logWidth",
log() {
k.debug.log(k.width());
},
};
},
logHeight() {
return {
id: "logHeight",
log() {
k.debug.log(k.height());
},
};
},
};
}
```
**Plugins with options**
```ts
function newLogPlugin(log: "width" | "height") {
return (k: KaboomCtx) => {
return {
logRes() {
return {
id: "hello",
log() {
k.debug.log(k[log]());
},
}
},
};
};
}
```
They work both
This was a big odyssey, basically I discovered `MergeObj<T>` doesn't work good when there are types with not required properties (for example, `Comp` type), so my first solution was doing this
```ts …
```
> empty components and plugins with options

- src/types.ts
Adds a comment explaining the usage of Texture.free() and it's importance
> Update types.ts - documentation comment for Texture.free()

- src/types.ts
The value is actually 200 in [source](https://github.com/replit/kaboom/blob/aa44a62999b6b510c24e317fc76ffc64524e9680/src/kaboom.ts#L3743C1-L3744C1)
> doc: fix OffScreenCompOpt.distance default value

- src/kaboom.ts
It is kinda annoying to change the `logMax` every time you want to debug, because probably you want to debug more than one thing, I think 10 lines is a better number by default.
> change default logMax to 10

- src/kaboom.ts
hello!!
we noticed that the debug ui is very pixelated when you set size and scale on a game (which my co-developer mentioned in #754).
i dug into the code a bit further, and saw that the framebuffer size is calculated from output size and pixel density – but not game scale! when i add this to the framebuffer size calculation, the debug ui works perfectly on upscaled games.
it does, of course, mean that the game renders more pixels. the performance impact seemed negligible on my tests though, since most of the rendering is done in the gpu anyways. this would be an easy fix to make the debug ui usable in low-resolution games.
> fix debug ui when scale & size are set

- src/kaboom.ts
- src/utils.ts
Native `String split()` can't handle emoji in strings correctly so it causes emoji display exception in text component.
I added a library to fix this.
> Fix emoji display in text

- examples/polygon.js
- src/kaboom.ts
- src/types.ts
Adds a `polygon` component so we can draw arbitrary shapes. 
Usage example: 
```
kaboom()
// Draw a square the hard way
add([
polygon([vec2(0,0), vec2(50,0), vec2(50,50), vec2(0,50)]),
pos(80, 120),
outline(4),
area(),
color(rgb(255,0,0)),
opacity(0.2),
])
```
> Add polygon component

- src/kaboom.ts
My game allows the user to enter text, when there is a zero-width character in the text component, the following error is generated causing the game to stop running, so I added a judgment to skip the rendering of the zero-width character.
```text
Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
```
https://kaboomjs.com/play?code=eJwlwkEKwjAQBdB15hSfbkygWnsAb%2BFOXMTMQIJtB9IBi6seoF7Sk4j6ePd4Ux19oKTTbLDFcEJk9hdyXYdzliq7GRFPqbp%2FFLaMlGONyaSiTLAsGAvzIAdyJov5pn%2Bv2%2B%2Frv29CSy7poNUfW3wHuoYPK3oqNw%3D%3D&example=add
> Skip zero-width character render

- src/kaboom.ts
fixed this:
```
> kaboom@3000.1.17 check
> tsc
src/kaboom.ts:4287:14 - error TS2339: Property 'isColliding' does not exist on type 'GameObj<PosComp | BodyComp>'.
4287        !this.isColliding(curPlatform)
~~~~~~~~~~~
Found 1 error in src/kaboom.ts:4287
```
> fix: err TS2339

- scripts/test.js
Addressing the Puppeteer Headless Deprecation Warning
```
Puppeteer old Headless deprecation warning:
In the near future `headless: true` will default to the new Headless mode
for Chrome instead of the old Headless implementation. For more
information, please see https://developer.chrome.com/articles/new-headless/.
Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.
```
> Fix puppeteer deprecated warning

- pkgs/create/create.js
The download function had "example" in the path name instead of "examples" which resulted in 404 errors when you tried to load in an example when creating a new kaboom project via npm
> Fix a typo in the create-kaboom script that causes examples to not be downloaded when using the download flag

- CHANGELOG.md
- src/gfx.ts
- src/types.ts
Arrays for shader uniforms. Soon to support struct like objects to be sent as a uniform. For example, Light a = { vec2 position, vec3 color } will be sent as a uniform such that if your shader has the struct Light, it will be able to accept that uniform to link specific variables together.
> Added support for arrays in uniforms.

- src/kaboom.ts
This PR fixes an issue where inside "beforePhysicsResolve" collisions could only be cancelled in the "source" GameObject's listener not inside the "target" GameObject's listener, because the reversed collision's `resolved` property wasn't checked.
> fix unresolveable collisions in beforePhysicsResolve

- src/kaboom.ts
This PR fixes a bug where when rendering styled text containing newlines or wrapping the index of characters wouldn't line up with their actual index into `charStyleMap`.
> Fix text styles breaking on newlines/wraps

- doc/dev.md
Removed outdated instructions:
- "run setup" is no longer a command in the node package
- localhost:8000/demo no longer exists
- /site is no longer in the project's directory
> chore(dev.md): remove old instructions from dev.md

- CONTRIBUTING.md
- Removed deprecated instructions on documentation section:
1. Currently `npm run build` does not generate a /site in project directory.
2. http://localhost:3000/ does not run.
- Added the following:
1. Instructions for Windows users. For those that had issues with esLint giving all errors, this might help. 
2. Provided a link to jsDoc for future doc contributors.
> chore(contributing.md): update contributing.md instructions

- doc/comp.md
- doc/dev.md
- doc/intro.md
- doc/migration-3000.md
- doc/publishing.md
- doc/setup.md
- doc/shader.md
- doc/tips.md
This PR is necessary for https://github.com/replit/kaboomsite/pull/5 working. This PR:
- add titles in every `doc/*.md` entry
- rewrites `doc/setup.md`
- simplify some phrases
- change the section *Using NPM* to *Setup your own Node.js environment*, I think it makes more emphasis that what you use at the end is node.js, and also the existence of more package managers besides npm, npm is only the package manager.
- clarify that what is shown in the esbuild mini tutorial is what` create-kaboom` does, I think it promotes (in my opinion) the best way to start kaboom.js projects.
> add titles to all doc files, rewrite setup

- src/types.ts
In the Kaboom.js docs, it's not clear how to use the `on()` function used to define custom events.
I tried to improve the docs to make usage more clear.
> Improved docs regarding custom events usage

- blog/3000.2.md
- doc/comp.md
- doc/dev.md
- doc/intro.md
- doc/migration-3000.md
- doc/publishing.md
- doc/setup.md
- doc/shaders.md
- doc/tips.md
This PR add some descriptions to `doc/` entries, this will be useful for SEO and maybe a future searching?
Also adds hidden: true in frontmatter of `blog/3000.2`, because that version is not released! Then the property will be used in replit/kaboomsite to hide it from view.
> add descriptions to doc entries, hide 3000.2v blog
