replit/kaboom

site/doc.js
site/examples.js

Simple addition to give the site a favicon, making it look more professional.

Add Favicon to Doc and Example Page

---

site/api.js

wrong method in docs

---

.gitignore

I use the Intellij editor and do not want to commit its config stuff.

Added Intellij IDEA to the gitignore file.

---

examples/mario.js

Mario game example crashes when game over so fixed it.

Lose screen when game over.

---

site/js/land.js

* Add Super Pong by SixBeeps
* Add 3D Space Shooter by ritza
* Add Satoshi Run by theNvN

Add other games in land.js

---

src/kaboom.ts

- keyDown
- keyPress
- keyPressRep
- keyRelease

fix: typings of keyXXX events

---

tut/intro.md

chore(intro.md): triangle -> rectangle

---

README.md

many deaths will be avoided if this is merged

FIX MEGABIG README ERROR

---

env/helper.ts
env/learn/Multiplayer.md
env/multiplayer.js
env/run.js
env/tsconfig.json
src/app.ts

Enable people to just edit `multiplayer.js` to program multiplayer logic with web sockets.

add multiplayer entry for template

---

src/kaboom.ts
src/types.ts

F6 to record is managed by kaboom debug mode, it makes sense to expose the recording handle under `debug`

Expose debug.curRecording

---

src/kaboom.ts
src/types.ts

Add color constants

---

site/pages/play.tsx

Currently it's triggering a page load which is horrifying.

[site] Use shallow routing for demo switching

---

README.md
doc/intro.md
site/pages/index.tsx

(will merge after next release)

Update API style in various places

---

src/math.ts

Hi I would like to help add testRectCircle :)
It is checked by
1 find the nearest point with circle
2 find the distant between the nearest point 
3 check the distant if it is less than circle's radius then it is intersect

Add testRectCircle

---

src/kaboom.ts

Pass arguments from enterState() to onStateEnter()

---

src/gfx.ts
src/kaboom.ts
src/types.ts

Is `letterSpacing` a more intuitive name?

[RFC] charSpacing -> letterSpacing?

---

src/math.ts

Use a method described [here](https://wrf.ecse.rpi.edu/Research/Short_Notes/pnpoly.html)

fix testPolygonPoint()

---

CHANGELOG.md
src/kaboom.ts

Fix onTouchEnd firing on touchmove

---

demo/children.js

A simple demo of parent-child relationships in Kaboom.

Added a parent-child demo

---

site/comps/Doc.tsx
site/pages/index.tsx

https://user-images.githubusercontent.com/9929523/145724748-7216f5b8-b918-4574-94c7-9ad72f82ce61.mp4

[site] Click on entry title to add url anchor

---

src/assets.ts

Improve loader error messages

---

demo/platformer.js
src/kaboom.ts
src/types.ts

Reverts replit/kaboom#467
`weight` fallback is not working

Revert "[RFC] `weight` -> `gravityScale`"

---

demo/ai.js
src/kaboom.ts

Don't check transitions if they're not defined

fix enterState() not working if transitions not defined

---

.github/ISSUE_TEMPLATE/bug.yml

Bug report minimal reproducable code now renders as shell.

Edit the bug report issue template

---

demo/layer.js
src/audio.ts
src/kaboom.ts
src/utils.ts

`console.warn` on deprecated functions

Add deprecation warnings

---

src/fps.ts
src/kaboom.ts

Move fps counter logic to its own module

Split fps counter

---

src/kaboom.ts
src/types.ts

Calculate on CPU instead of using uniforms, the benchmark shows no perf diff but much cleaner and maintainable
Also contains a minor refactor to separate module states instead of one big state.

Use simpler camera transform mechanism

---

src/kaboom.ts

Fix fixed ui not fixed

---

CHANGELOG.md
demo/camera.js
src/kaboom.ts

Long standing problem #305 #407 #448
TODO: fix fullscreen mouse position with letterbox

Fix letterbox view and mouse position in letterbox / stretch / fullscreen mode

---

CHANGELOG.md
demo/draw.js
src/kaboom.ts
src/types.ts

https://user-images.githubusercontent.com/9929523/151115421-595d3b57-4a58-4f02-9c35-da47bebf709b.mp4
```js
// pass a color for each vertice
drawPolygon({
pts: [ vec2(30, 60), ... ],
color: [ rgb(128, 128, 255), ... ],
})
// pass the start and end color
drawRect({
width: width(),
height: height(),
gradient: [ Color.GREEN, Color.BLUE ],
})
```

add `drawGradient()`

---

src/types.ts

fixes the docstring for passing in custom chars

add chars to loadFont

---

CHANGELOG.md
demo/draw.js
src/kaboom.ts
src/types.ts

https://user-images.githubusercontent.com/9929523/151273265-986c166a-6af0-4e02-ae4a-483934b62350.mp4

Add `drawMasked()` and `drawSubtracted()`

---

create/create.js
create/package.json

- added a simple argument parser
- support pulling demos from the official demo list with `--demo <name>`
- support starting the dev server right away with `--start`

[create-kaboom] Support pulling demo and starting server

---

demo/draw.js
src/kaboom.ts
src/types.ts

To check for if any key is currently down

Support isKeyDown() without args

---

src/kaboom.ts
src/types.ts
src/utils.ts

Added a helper class `EventHandler` to replace repeating event handling code

Use EventHandler for events

---

demo/kaboom.js
src/kaboom.ts
src/types.ts
src/utils.ts

`SpriteData` and `SoundData` that can be loaded independent of the asset system, `loadSprite()` and `loadSound()` are wrappers that integrates with the asset system

Add classes for asset data

---

src/kaboom.ts
src/utils.ts

Fixes #531. Clear all events on `game.root` on scene change

Fix onupdate events getting called after scene change

---

CHANGELOG.md
demo/size.js
src/kaboom.ts
src/types.ts

added an internal `drawUnscaled()` for drawing stuff like debug UI, error message, and loading screen where they should be unaffected by user's viewport / scale settings

Fixed scaling for internal UI

---

README.md

Hi! I have nothing to say, just if u like it, merge and if you not, dont merge :smile:

Update README.md :book: 

---

src/kaboom.ts

Silent errors with things like this are just plain unhelpful

Add error message on object destruction failure

---

src/kaboom.ts

it's only one line, but this line could change everything...
* support to pingpong param in `loadAseprite`

support to pingpong option in `loadAseprite`

---

site/next.config.mjs

To improve on the issue of authenticity when providing a Discord Server link

Added a redirect to Discord Server

---

blog/markjam-3.md

MarkJam 3 Blog Post

---

blog/markjam-4-winners.md

it seems it is always better to put a line break before each image

fix readme format

---

src/kaboom.ts

TODO: don't assume 1 as start opacity

---

src/kaboom.ts
src/scenes.js
src/types.ts

Scenes holds an array of scenes that will either stay in those scenes or get deleted in those scenes depending on the scene stay property.

Added Scenes/SceneStay properties to stay() comp

---

CHANGELOG.md
examples/postEffect.js
examples/postprocess.js
examples/shader.js
examples/shaders/invert.frag
examples/shaders/pixelate.frag
examples/shaders/vhs.frag
src/kaboom.ts
src/types.ts

This PR adds `usePostEffect()` which lets you use a shader for full screen visual effects. Also sets up some framebuffer stuff.

Post effect

---

doc/20-eatbomb.md

Make iframe work

---

doc/setup.md

Fix broken link

---

doc/sections/Debug.md
examples/concert.js
examples/hover.js
examples/shooter.js
src/types.ts

* add some final dots
* update debug doc description
* some details
* update `addLevel` and `play()` example code
* reposition of elements in `hover` example
* fix `concert` and `shooter` examples

fix details, add dots and update examples code

---

doc/setup.md

The file type of the horse sound was wrong (png), so i changed it to mp3.
also fixed a typo.

Fix file type in setup.md.

---

src/kaboom.ts

feat: support pingpong loop for sprite anim

---

doc/intro.md

updated the inspect image in intro doc

update intro inspect img

---

src/types.ts

Fix example in types.ts

---

src/types.ts

The second argument is missing
https://github.com/replit/kaboom/blob/master/src/kaboom.ts#L4445

Update health() in types.ts

---

src/types.ts

Fixing doc mistake

---

blog/2000.md
examples/component.js

https://kaboomjs.com/play?example=component

fix spelling "unnamed" in examples/component.js

---

examples/overlap.js
src/math.ts
src/types.ts

Shapes now have the following methods
collides(shape: any): boolean - Test overlap with any other shape
contains(point: Vec2): boolean - Test if a point is contained by the shape

Add generic shape matching methods + example to test overlap tests

---

examples/raycastShape.js
src/math.ts
src/types.ts

Adds raycast(origin, direction) to all shapes, as well as a laser example

raycasting shapes

---

src/app.ts

haven't tested it but it shouldn't break things

Added mouseDeltaPos support for touch control

---

src/types.ts

Added a few examples of how scale( ) can be used in types.ts file

chore(types.ts): add scale() examples in docs

---

doc/setup.md

The tutorial is linking to an older version of Kaboom

Update Kaboom unpkg version in setup doc

---

CONTRIBUTING.md
examples/examples.json
examples/fadeIn.js
src/kaboom.ts
src/types.ts

Changed fadeIn to use opacity so it can fade into 0.5 for example
Changed Contributing.md because there was "" around linebreak style and that isnt correct
Added fadeIn example so you can learn fadeIn
Changed JSDoc to have a fadeIn example

fadeIn() now uses opacity to figure out the final opacity to fade into
